
CREATE TABLE IF NOT EXISTS NhanVien (
    MaNV VARCHAR(20) PRIMARY KEY,
    TenNV VARCHAR(100) NOT NULL,
    ChucVu ENUM('quan_ly', 'nhan_vien') NOT NULL,
    SoDienThoai VARCHAR(20),
    Username VARCHAR(50) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'dang_lam'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS KhachHang (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) UNIQUE NOT NULL,
    Email VARCHAR(100) DEFAULT '',
    DiaChi VARCHAR(255) DEFAULT '',
    NgaySinh DATE DEFAULT NULL,
    GioiTinh VARCHAR(10) DEFAULT '',
    DiemTichLuy INT NOT NULL DEFAULT 0,
    CapBac VARCHAR(20) NOT NULL DEFAULT 'thuong',
    TongChiTieu INT NOT NULL DEFAULT 0,
    SoLanMua INT NOT NULL DEFAULT 0,
    NgayTao DATETIME DEFAULT NULL,
    LanMuaCuoi DATETIME DEFAULT NULL,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'dang_hoat_dong',
    GhiChu TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NhaCungCap (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(150) NOT NULL,
    SoDienThoai VARCHAR(20),
    DiaChi VARCHAR(255),
    GhiChu TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NguyenLieu (
    MaNL VARCHAR(20) PRIMARY KEY,
    TenNL VARCHAR(150) NOT NULL,
    DonViTinh VARCHAR(20) NOT NULL,
    SoLuongTon DECIMAL(12,2) NOT NULL DEFAULT 0,
    MucCanhBao DECIMAL(12,2) NOT NULL DEFAULT 5,
    GiaNhapTB INT NOT NULL DEFAULT 0,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'con_hang'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SanPham (
    MaSP VARCHAR(20) PRIMARY KEY,
    TenSP VARCHAR(150) NOT NULL,
    LoaiSP VARCHAR(50) NOT NULL,
    GiaBan INT NOT NULL,
    HinhAnh VARCHAR(255) DEFAULT '',
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'dang_ban',
    TrangThaiKhoChinhTay VARCHAR(20) NOT NULL DEFAULT 'tu_dong',
    GhiChuKho TEXT,
    MoTa TEXT,
    CONSTRAINT chk_trang_thai_sanpham CHECK (TrangThai IN ('dang_ban', 'ngung_ban')),
    CONSTRAINT chk_trang_thai_kho CHECK (TrangThaiKhoChinhTay IN ('tu_dong', 'con_hang', 'sap_het', 'het_hang'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CongThuc (
    MaSP VARCHAR(20) NOT NULL,
    MaNL VARCHAR(20) NOT NULL,
    DinhLuong DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (MaSP, MaNL),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE,
    FOREIGN KEY (MaNL) REFERENCES NguyenLieu(MaNL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HoaDon (
    MaHD VARCHAR(20) PRIMARY KEY,
    ThoiDiemLap DATETIME NOT NULL,
    MaKH VARCHAR(20),
    TenKH VARCHAR(100) NOT NULL,
    CapBacKhach VARCHAR(20) DEFAULT 'thuong',
    MaNV VARCHAR(20) NOT NULL,
    TenNV VARCHAR(100) NOT NULL,
    TongTruocGiam INT NOT NULL DEFAULT 0,
    GiamGiaCapBac INT NOT NULL DEFAULT 0,
    DiemSuDung INT NOT NULL DEFAULT 0,
    GiamGiaDiem INT NOT NULL DEFAULT 0,
    TongTien INT NOT NULL,
    DiemCong INT NOT NULL DEFAULT 0,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'da_thanh_toan',
    PhuongThucThanhToan VARCHAR(20) DEFAULT 'tien_mat',
    TienKhachDua INT NOT NULL DEFAULT 0,
    TienThua INT NOT NULL DEFAULT 0,
    GhiChu TEXT,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ChiTietHoaDon (
    MaHD VARCHAR(20) NOT NULL,
    MaSP VARCHAR(20) NOT NULL,
    TenSP VARCHAR(150) NOT NULL,
    SoLuong INT NOT NULL,
    DonGia INT NOT NULL,
    Size VARCHAR(10) NOT NULL DEFAULT 'M',
    GhiChu TEXT,
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ThanhToan (
    MaTT VARCHAR(20) PRIMARY KEY,
    MaHD VARCHAR(20) UNIQUE NOT NULL,
    SoTienKhachDua INT NOT NULL DEFAULT 0,
    SoTienThoi INT NOT NULL DEFAULT 0,
    HinhThuc VARCHAR(20) NOT NULL DEFAULT 'tien_mat',
    ThoiDiemThanhToan DATETIME NOT NULL,
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PhieuNhap (
    MaPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME NOT NULL,
    MaNCC VARCHAR(20) NOT NULL,
    TenNCC VARCHAR(150) NOT NULL,
    MaNV VARCHAR(20) NOT NULL,
    TenNV VARCHAR(100) NOT NULL,
    TongTienNhap INT NOT NULL,
    GhiChu TEXT,
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ChiTietPhieuNhap (
    MaPN VARCHAR(20) NOT NULL,
    MaNL VARCHAR(20) NOT NULL,
    TenNL VARCHAR(150) NOT NULL,
    SoLuongNhap DECIMAL(12,2) NOT NULL,
    DonGiaNhap INT NOT NULL,
    ThanhTien INT NOT NULL,
    PRIMARY KEY (MaPN, MaNL),
    FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN) ON DELETE CASCADE,
    FOREIGN KEY (MaNL) REFERENCES NguyenLieu(MaNL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
